### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by jhaemin** [paywteam/eodiro-server#41]
![7E02FB34-6E3D-4657-94AA-D41A0B5345FF](https://user-images.githubusercontent.com/19797697/82276304-d6d04c80-99bf-11ea-98ee-31f5476cf356.jpeg)

2MB of ram leaks every 5 min.

### Suspicion

- The **Notice Watcher**, a new feature introduced few days ago

**Comment by JeongBin0227** [comment]
I hope this issue will be fixed soon :(

**Comment by jhaemin** [comment]
Gotcha!! 🐶

**Comment by jhaemin** [comment]
**_Good News_**

It reaches 149\~150mb and it seems not growing anymore. Total memory consumption also stops at 840\~842mb.

**Comment by jhaemin** [comment]
**_Bad News_**

It keeps eating more and more memories.

**Comment by jhaemin** [comment]
Total memory consumption grows to 1GB (mostly eaten up by `mysqld`). But still the eodiro-server consumes 150~155mb.

**Comment by jhaemin** [comment]
Witnessed duplicate Puppeteer Chromium instances.

![Screen Shot 2020-05-21 at 10 02 28 AM](https://user-images.githubusercontent.com/19797697/82512153-2fcbec00-9b4a-11ea-8483-a0bcee19242d.png)

**Comment by JeongBin0227** [comment]
Wow!! You're such a wonderful kid, I thought you'd do it
Now that surprised puppy is smiling

**Comment by jhaemin** [comment]
![Screen Shot 2020-05-22 at 10 36 32 AM](https://user-images.githubusercontent.com/19797697/82622237-3cb71100-9c18-11ea-8256-90244d21ae0e.png)

**Comment by jhaemin** [comment]
Stops at ~500mb

**Comment by jhaemin** [comment]
This issue was produced by Zombie.js (https://github.com/assaf/zombie/issues/672)

It will be replaced by Puppeteer in the next release.

![FFC1A525-84FD-4643-AF0D-2B47D64C136D](https://user-images.githubusercontent.com/19797697/82871098-f80add00-9f6b-11ea-8391-c9bc188e6ab4.jpeg)

@JeongBin0227, thanks for participating

**Comment by JeongBin0227** [comment]
Wow! It's really a celebration.
Are you your puppy home?
It's so cute, I can't even see my teeth
